id: P005465
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4250
  title: འཛམ་ཐང་ཆོས་རྗེ་དགོན་ཆེན་གྱི་གདན་རབས།
  author: ''
  volumes:
    6ab53c76549943cdb8d582fdaaeda8fb:
      image_group_id: I1KG4971
      title: ''
      volume_number: 1
      total_pages: 164
      base_file: v001.txt
